### ISSUE TITLE
Buscador que permita buscar entre todas las canciones, podcasts, álbumes, listas de reproducción y usuarios

### ISSUE THREAD

**Issue by enrirf** [UNIZAR-30226-2020-02/Back-End#25]

**Comment by dsubias** [comment]
Con el parametro KeyWord las función retorna todas las canciones, albumes, playlist no privadas, usuarios y podcast,  junto con su respectiva informacion , cuyos nombres contengan el argumento KerWord como substring

Si se requieren mas campos de los elementos recuperados comunicar al equipo de backend
